version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: django_try.settings.test
    SECRET_KEY: nosecret
    DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
    DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
    STREAM_INCOMING_PRIVATE_KEY: changeme
    STREAM_INCOMING_PUBLIC_KEY: changeme
    GOOGLE_API_KEY: changeme
    OPBEAT_ENABLED: False

phases:
  install:
    commands:
      - echo Installing Python...
      - apt-get update  # Update package list
      - apt-get install -y python3 python3-pip  # Install Python and pip
      - python3 -m pip install --upgrade pip  # Upgrade pip to the latest version
      - pip install django gunicorn
  pre_build:
    commands:
      - echo Prebuild ops
      - export LANG=en_US.UTF-8
  build:
    commands:
      - echo Building the application 
      - python3 manage.py migrate  # Run migrations
      - python3 manage.py test  # Run tests
      - python3 manage.py collectstatic --noinput  # Collect static files without user input
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
